### ISSUE TITLE
Issue related to website - didn't know where to report...

### ISSUE THREAD

**Issue by dothebart** [wloop/wlib-json#12]
https://medium.com/waterloop/how-we-built-the-first-canadian-hyperloop-pod-40c4d4fb1dee

the video with the air pods will not render properly

**Comment by dhillondeep** [comment]
@cchan @Ambyjkl

**Comment by cchan** [comment]
Thanks for the report @dothebart! For things like this it's usually best to contact us at admin@teamwaterloop.ca, but I'll fix this! :)

**Comment by Mogball** [comment]
the repo for the website would be more appropriate too lol

**Comment by cchan** [comment]
Fixed I think
